language: node_js
node_js:
- node
cache: npm

stages:
  - lint
  - build
  - deploy

jobs:
  include:
    - stage: lint
      name: "Linter check"
      script: npm run lint
    - stage: build
      name: "Build assets"
      script: npm run build
    - stage: deploy
      name: "Deploy to Firebase"
      script: skip
      deploy:
        skip_cleanup: true
        provider: firebase
        token:
          secure: oPZd7bdh66HcxdXqiJorcQtVx/qlvBEQ0pFxxv0Yyit+Quh+nEnBSXrxgpl8R+zDACW/jns6F2wjSV6Z8c6dHF50wL+gdhXvKnjGQPvOWueFUgbt+gsOD4g8VWF3fWT0osswGutvPWiXOZRJHKCCsWXs1siLd6OZftIBkEa4oqobREK8lCNTtaxjjxQpDLpkgA+7xxobeftHy4S+2K4/uz8t4ydCt22URDcLg9AO8KawapX/Z8Kcr/S5RGYEMUBMJ3ATLzWuDh4IOhg7zRPNX7Z6GxaTWUbbbE/qeiXh3B0qB+dQJo7RfE6rLhuET6GA1l4+6mbkNQFXUqjmz8WN5YXUzJSdYssAy7SV8y6z75jmJP55cAKR7+6v5IpK6pHUc+aW1IoJZSgMvyBlyM89IECTKyxw4gYMj3MNQGrL1zFt535QhqEQmPhotxACQ3d594X6K57xz1jfLIheECC2hv9AdS1C+k+PYzjkUF0DkubFYtyOUAlJwjWIStHtG4g7/RddhEMXaDCqx4cQgMuWcc7EmY9w0db6FeiBuInrKopHetCFgwf/yYCaoIvlv3R6dYjtiGbebouMI/ivnYaRp/gVmJscq/y5KleFFv406agQHuoZ/EVimnX2xE4Q/WRPa4/j0ZrdKXYIZRB6QQVJ78+iClDTo9W2JbTeo19ftOI=